### ISSUE TITLE
class BaseGradientBossting,  there is a braket when the estimator is put in device

### ISSUE THREAD

**Issue by Jacob-Chew** [AaronX121/Ensemble-Pytorch#4]
class BaseGradientBossting(BaseModule):
# Base estimators
        self.estimators_ = nn.ModuleList()
        for _ in range(self.n_estimators):
            self.estimators_.append(estimator().to(self.device))
if initial a class BaseGradientBossting, a forward function in estimator will be excuted and it will be a wrong for there is no inputs

**Comment by AaronX121** [comment]
Hi @Jacob-Chew, thanks for reporting!

Could you please add the traceback information showing that something is wrong?

I have just tested the `GradientBoostingClassifier` on PyTorch 1.7.0 using the script in `/exmaples`, and the program moves to the training stage without throwing any error.

**Comment by AaronX121** [comment]
Let's see if I get your point, the backet after `estimator` is necessary because what we want is that each element in `self.estimators_` corresponds to an individual base estimator **after instantiation**.  You can check the loop at [Here](https://github.com/AaronX121/Ensemble-Pytorch/blob/master/torchensemble/gradient_boosting.py#L88), each estimator is directly used for data forward and training.

**Comment by Jacob-Chew** [comment]
I think I have found the reason. In my code, what I passed to estimator is a instance of the network class instead of the class object, so when excute estimator().to(self.device)  it will make it forward.

**Comment by AaronX121** [comment]
Maybe I should clarify or add more options on the input argument `estimator`. Thanks for reporting! ; )
